### ISSUE TITLE
Fixed vendor version

### ISSUE THREAD

**Issue by ZAYEC77** [sanchezzzhak/kak-clickhouse#1]
@sanchezzzhak 
Hello, can you change version of `yii2-httpclient` in your [`composer.json`](https://github.com/sanchezzzhak/kak-clickhouse/blob/master/composer.json#L20).
Exact version conflicts with other packages.
You can use something like this `"yiisoft/yii2-httpclient": "^2.0.0"`.

Please, look on [composer docs](https://getcomposer.org/doc/articles/versions.md).

**Comment by sanchezzzhak** [comment]
Hello, thank you for finding Bugs.
composer fixed;
