### ISSUE TITLE
Implement PREWHERE clause

### ISSUE THREAD

**Issue by sleptor** [sanchezzzhak/kak-clickhouse#12]
This clause has the same meaning as the WHERE clause. The difference is in which data is read from the table. When using PREWHERE, first only the columns necessary for executing PREWHERE are read. Then the other columns are read that are needed for running the query, but only those blocks where the PREWHERE expression is true.

https://clickhouse.yandex/reference_en.html#PREWHERE+clause

**Comment by sanchezzzhak** [comment]
in the new branch querySpecialSection some implementation.

**Comment by sleptor** [comment]
works! thank you so much!
