### ISSUE TITLE
Добавить БД в \kak\clickhouse\Schema::loadTableSchema

### ISSUE THREAD

**Issue by alekson** [sanchezzzhak/kak-clickhouse#22]
Примерно так - http://joxi.ru/BA00j0TB4vJzAy

В процессе разработки набор и тип полей меняется, а в старых БД остается старая версия 
 - string, а в новой UInt64.

Делая запрос SELECT * FROM system.columns WHERE table='tbl' FORMAT JSON

Оно получается данные сразу по всем БД и выпадает старый вариант, в итоге идет неправильный каст и ошибка 

 `Code: 53, e.displayText() = DB::Exception: Type mismatch in IN or VALUES section. Expected: UInt64. Got: String, e.what() = DB::Exception`

**Comment by sanchezzzhak** [comment]
добрый день, спасибо за найденную ошибку, исправления будут сегодня.
