### ISSUE TITLE
typecast() error

### ISSUE THREAD

**Issue by Galyam** [sanchezzzhak/kak-clickhouse#24]
counter_id Nullable(UInt32)

   $client->createCommand(null)
    ->insert('stat', [
        'event_data' => date('Y-m-d'),
        'counter_id' => 122
    ])->execute();

пытается вставить '122' вместо 122.

В случае если поле типа UInt32 - все нормально

**Comment by sanchezzzhak** [comment]
привет возможно иза typecast Nullable, проверим
