### ISSUE TITLE
activerecord не загружает модели

### ISSUE THREAD

**Issue by pyhbka** [sanchezzzhak/kak-clickhouse#27]
При любом раскладе возвращает массив
как пример
TestModel::find()->one(); вернет массив
TestModel::find()->all(); вернет массив массивов
моделька ни разу не прогрузилась.

TestModel - https://github.com/sanchezzzhak/kak-clickhouse#activerecord-model
как тут, ничего лишнего только rules добавил, связей нет.

пока смог решить добавлением двух методов в класс kak\clickhouse\ActiveQuery из yii\db\ActiveQuery, методы one и populate

Что я не так делаю ? :(

**Comment by alexgivi** [comment]
https://github.com/sanchezzzhak/kak-clickhouse/pull/29
