### ISSUE TITLE
Сломали ActiveQuery

### ISSUE THREAD

**Issue by utmstat** [sanchezzzhak/kak-clickhouse#31]
https://cl.ly/434c1ce0b30f

Строка 74, должно быть 

` if ($row !== null) {`

**Comment by utmstat** [comment]
Почините плз, сломался боевой проект

**Comment by sanchezzzhak** [comment]
привет, подправим

**Comment by sanchezzzhak** [comment]
исправил

**Comment by utmstat** [comment]
Спасибо, был нежданчик сегодня, в целом активно пользуемся )
