### ISSUE TITLE
UInt64 update/insert

### ISSUE THREAD

**Issue by navel** [sanchezzzhak/kak-clickhouse#33]
В `yii2\db\Schema.php:633` в функции `getColumnPhpType()` для UInt64 выставляется значение string. Это мешает вставлять и обновлять значения.
php не может работать с подобными числами, как вариант можно заменять такие строки на `'toUInt64($value)'`

**Comment by sanchezzzhak** [comment]
Можно пример кода, при котором у вас возникает проблема.

**Comment by navel** [comment]
> Можно пример кода, при котором у вас возникает проблема.
Сохранение любой модели у которой есть поле UInt64.

Yii правильно делает, что работает с этими числами как со строками, ибо в php в int они не умещаются. Но и в запрос на insert/update они подставляются с кавычками.

**Comment by sanchezzzhak** [comment]
Проверь, я залил фикс, я в тестах проверил запись вставляет.

**Comment by navel** [comment]
Проверил. Работает, спасибо
