### ISSUE TITLE
Баг в SqlDataProvider . Getting unknown property: yii\db\Query::sample

### ISSUE THREAD

**Issue by Alexz29** [sanchezzzhak/kak-clickhouse#34]
В файл kak/clickhouse/data/SqlDataProvider.php

```php
use kak\clickhouse\Query;
protected function prepareTotalCount()
    {
        return (new Query([
            'from' => ['sub' => "({$this->sql})"],
            'params' => $this->params,
        ]))->count('*', $this->db);
    }
```

Так как в версии yii 2.0.16
вот такая ошибка 

`
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: yii\db\Query::sample
`

**Comment by sanchezzzhak** [comment]
Обновите пакет, ошибка исправлена в старых версиях в методе `prepareTotalCount` была проверка если значение уже известно то не делать запрос.

**Comment by Alexz29** [comment]
Привет спасибо что оперативно ответил! Но в таком случае не будет пагинация работать.

Нужно именно вот этот код поставить

`use kak\clickhouse\Query;
protected function prepareTotalCount()
    {
        return (new Query([
            'from' => ['sub' => "({$this->sql})"],
            'params' => $this->params,
        ]))->count('*', $this->db);
    }
`

а так же не забыть прописать use kak\clickhouse\Query;

**Comment by sanchezzzhak** [comment]
Код, который там используется нам не нужен.
При запросе в prepareModels, где отправляется запрос - мы уже знаем сколько записей всего доступно без лимита.

G
```
$q = (new \kak\clickhouse\Query())->from('stat')
    ->where(['event_date' => '2017-05-01' , 'user_id' => 5 ])
    ->offset(0)
    ->limit(100);

$command = $q->createCommand();
$result  = $command->queryAll();

var_dump($command->getCountAll());    // rows count before limit at least	

```

**Comment by agilov** [comment]
У меня то же самое после обновления фреймворка
