### ISSUE TITLE
подскажите как исправить ошибку при создании бэкапа clickhouse

### ISSUE THREAD

**Issue by Dori-Grey** [sanchezzzhak/kak-clickhouse#42]
При создании бэкапа выводится много записей:
Received exception from server (version 19.6.2):
Code: 53. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Type mismatch in IN or VALUES section. Expected: Date. Got: Int64. 
Скажите насколько критично данное сообщение и как исправить.

CentOS Linux release 7.6.1810 (Core) 
ClickHouse client version 19.6.2.1
ClickHouse server version 19.6.2

скрипт создания бэкапов:
  clickhouse-client  --query="SELECT partition, table, database FROM system.parts WHERE active;" > /tmp/.clickhouse_temp_dbs.txt

  while read STRING; do
    CH_DB=$(echo ${STRING} | awk '{print $3}')
    CH_TBL=$(echo ${STRING} | awk '{print $2}')
    CH_PT=$(echo ${STRING} | awk '{print $1}')

    clickhouse-client --query="ALTER TABLE $CH_DB.$CH_TBL FREEZE PARTITION $CH_PT";

  done < /tmp/.clickhouse_temp_dbs.txt
  tar czhpf - /var/lib/clickhouse/shadow/ /var/lib/clickhouse/metadata/ > /var/lib/clickhouse/dir

**Comment by sanchezzzhak** [comment]
лучше всего спросить в телеграм канале https://t.me/clickhouse_ru 

я делаю бекапы очень просто 
```
select * from table_name  FORMAT NATIVE > dump.native
```
