### ISSUE TITLE
Can't use other than default database

### ISSUE THREAD

**Issue by mxzwrnz** [sanchezzzhak/kak-clickhouse#5]
I tried to set the config parameter 'database' to my productive database and I also tried to set the table to 'db.table' which both returns an error.
How to set a database properly?

**Comment by mxzwrnz** [comment]
I found something that might cause the error. The URL created when using a database in the config ends with a /, which is interpreted as part of the database name by the Clickhouse Server. The server the  throws an exception.
Where and how excatly is the building of the URL done?

**Comment by sanchezzzhak** [comment]
Hello, in the coming hours will make a fix

**Comment by sanchezzzhak** [comment]
Fix done, thank you very much

**Comment by mxzwrnz** [comment]
Doesn't work for me. The $url property in Request is empty and can't be trimmed.
If I modify afterPrepraeUrl() in Request.php to the following it works:
`private function afterPrepareUrl()
    {
        $url = $this->getFullUrl();
        if (strpos($this,'?') !== false) {
            $url = trim($url,'/');
            $this->setUrl($url);
        }
    }`

**Comment by sanchezzzhak** [comment]
You can link an example, it can be seen at debug-panel -> log

**Comment by mxzwrnz** [comment]
I have the code locally on my machine. But here's a screen:

![image](https://cloud.githubusercontent.com/assets/24412208/21392911/5b00d9ba-c792-11e6-852c-153f1f2fc03f.png)

If you try to output the $url in the function afterPrepareUrl you get an empty string. Maybe there's the problem?

**Comment by sanchezzzhak** [comment]
i uploaded your fix, pls test
