### ISSUE TITLE
Создание миграций

### ISSUE THREAD

**Issue by nolka** [sanchezzzhak/kak-clickhouse#53]
Привет! Помогите пожалуйста разобраться, как правильно создавать миграции? В обычных Yii2 миграциях используя raw sql, либо есть какие то другие способы?

**Comment by lastrockstar** [comment]
Привет,
я лично  создал отдельный консольный контроллер миграций для Clickhouse
и держу их в отдельной папке.

Сами миграции ты можешь создавать как в RAW, так и через билдер.

https://gist.github.com/lastrockstar/57400d6d3a924c274356d26c9c9e022f

**Comment by nolka** [comment]
Спасибо, примерно к такому же подходу я и пришел)
