### ISSUE TITLE
why disable query cache?

### ISSUE THREAD

**Issue by qihuajun** [sanchezzzhak/kak-clickhouse#55]
When creating query command, this component's code disable cache. 

Here is the code in `\yii\db\Query`:

 ```
$command = $db->createCommand($sql, $params);
 $this->setCommandCache($command);
```
the code in `\kak\clickhouse\Query`:

```
$this->_command = $db->createCommand($sql, $params);
```

Are there any problems about this component's supporting for query cache?

**Comment by sanchezzzhak** [comment]
this method was added much later than the implementation of the clickhouse component

the setCommandCache method was needed only for this case
```php
$query = new Query;
$query->cache(10);
$command = $query->createCommand();
var_dump($command->queryCacheDuration);  // 10
```
Now, it should work.

---
Working with the cache is the same as in a standard component


```php

// QueryBuilder
$dd = new kak\clickhouse\Query();
// ...
$dd->cache(5);
$dd->all();

// DAO
$dd = $db->createCommand($sql);
$dd->cache(5);
// ...
$dd->queryAll();
```

**Comment by qihuajun** [comment]
@sanchezzzhak Thanks!
