### ISSUE TITLE
Incorrect response on ActiveRecord->count()

### ISSUE THREAD

**Issue by rowdyroad** [sanchezzzhak/kak-clickhouse#7]
Hi, again.

I've found this issue when working with ActiveRestController.

Index action makes count(*) query (for pagination). So, your component return an array not scalar int value.

Little Example:
`class Measuring extends \yii\db\ActiveRecord`
`class MeasuringReport extends \kak\clickhouse\ActiveRecord`

`
var_dump(\app\models\Measuring::find()->count());
var_dump(\app\models\MeasuringReport::find()->count());
`
Response is:
> int(4308936)
> array(1) { [0]=> array(1) { ["COUNT()"]=> string(7) "4308936" } }

Now I'm thinking about way to fix it, we can think together))

**Comment by sanchezzzhak** [comment]
Hi, yes this is error (
I don't use ActiveRecord, just DAO, but interested to fix it up

**Comment by sanchezzzhak** [comment]
Tnx

**Comment by rowdyroad** [comment]
без проблем ;)
