### ISSUE TITLE
Command::batchInsertFiles doesn't work

### ISSUE THREAD

**Issue by sleptor** [sanchezzzhak/kak-clickhouse#9]
get error for table with name "stat":

Code: 36, e.displayText() = DB::Exception: Neither structure nor types have not been provided for external table stat. Use fields stat_structure or stat_types to do so., e.what() = DB::Exception

**Comment by sanchezzzhak** [comment]
Today, we fix, pls wait

**Comment by sanchezzzhak** [comment]
hi, error fixed.

**Comment by sleptor** [comment]
thanks!
